# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b0c36b2f1ab8b6e2360d0c3e008bc5e5f12e5d77ca19e06dff712d6ebb4468764fbc4eea3b16c3b70946372c4f5ba91533b02871693c65eb0ab7c8876a2488a

test:
  secret_key_base: 9fd1a69e5c60fc03ba141e55821f44f97884be6ba9f3cd4691a2200ff54259254528db2746ab8f5c0a37f64c2b924e830f47c0a68534e1fc837ad72b31128bc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
